### ISSUE TITLE
MySQL support `0000-00-00 00:00:00` but sqlpad throw `Invalid time value`

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#1022]
@rickbergfalk, please look this issue, is it belong to the bug of the sqlpad, or that need a `zero date to null` feature comes from the mysql library?
![image](https://user-images.githubusercontent.com/1353036/122042965-63d91580-ce0d-11eb-81e5-c596119bc1ba.png)
![image](https://user-images.githubusercontent.com/1353036/122043054-7b180300-ce0d-11eb-872d-38b9b4ef869b.png)

**Comment by rickbergfalk** [comment]
I'm not sure what the solution would be here. This looks to be a limitation of the driver (and JavaScript) https://github.com/mysqljs/mysql/issues/1040. 

The `mysql` driver has a `dateStrings` option https://www.npmjs.com/package/mysql#connection-options to return dates as strings instead of JS date objects, which might work... but SQLPad inspecting the string result might try and convert it back to a date. Not sure what will happen to the 0 dates in that case.

**Comment by dengc367** [comment]
Thank you. I setup the `dateStrings` to `true` ,and it's fixed, and can query successfully and display zeros format string when the value of `datetime` type column is `zero`s. I have created one PR #1023 , Please review it, if you have time. @rickbergfalk
