### ISSUE TITLE
PostgreSQL query date column is change the date result to UTC timezone.

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#1028]
I am using SQLPad in Asian/Shanghai +8:00 timezone, and query the table with a date type column in PostgreSQL connection, but the value display on SQLPad of date type column are convert into the UTC timezone,  example: the real value in PostgreSQL  database is `2021-01-03`, but SQLPad display the UTC result: `2021-01-02 16:00:00`, like the following example on the screenshot, I just need to display as it is, so that is beset and entrapped as if in mire. I change the linux system locale and system timezone to `Asian/Shanghai`, but it is not solved.  Do you have any nice solution? @rickbergfalk I have just look at the https://github.com/brianc/node-postgres library, and there are some issues described like the same phenomena, example: https://github.com/brianc/node-postgres/issues/1746, which not have a [connection parameter](https://github.com/brianc/node-postgres/blob/4b229275cfe41ca17b7d69bd39f91ada0068a5d0/packages/pg/lib/connection-parameters.js#L48)  such like [`dateStrings`](https://github.com/sqlpad/sqlpad/pull/1023) in MySQL/MySQL2 library, which can automatically convert the date to string.

![image](https://user-images.githubusercontent.com/1353036/122481014-88491380-d000-11eb-9fab-8bfe14d5446a.png)

**Comment by dengc367** [comment]
I change the process environment parameter `TZ` from `Asian/Shanghai` to `UTC`, which can read using `process.env.TZ` parameter by `node-postgres` library, and then this problem is solved. 
```
export TZ=UTC;
node server/server.js --config config.env
```
Check out the detailed [Reference Source](https://node-postgres.com/features/types)

**Comment by nsitbon** [comment]
Hi I have the same issue : a simple `SELECT TO_DATE('2022-02-23', 'YYY-MM-DD')` on Postgresl returns a correct DATE with psql (2022-02-23) but returns an invalid timestamp with Sqlpad 2022-02-22 23:00:00. I don't understand why I got a timestamp instead of a plain DATE ? I'm not running the sqlpad myself so I can't change anything and even if I could we're using it with hundreds of databases so I can't change the timezone globally.
Best regards
