### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by webysther** [sqlpad/sqlpad#1188]
Looking the suggestions was hard to find a alternative more light and easy to use like sqlpad, since project is about to die in next few years, maybe consider put in the list this two links:

[CloudBeaver](https://github.com/dbeaver/cloudbeaver)
[Awesome Database Tools - GUI](https://github.com/mgramin/awesome-db-tools#gui)

**Comment by webysther** [comment]
The project is great! But is "legacy project in maintenance mode", for a organisation is a real risk. I just recommended to put more options on the main page, I find one that makes sense for my homelab. Like PHPMyAdmin and other similar projects is very serious the money you possible lost if for wrong configuration expose for web or dont use anothers solutions for security. But I not the developer, this is my understand about the move.

**Comment by rickbergfalk** [comment]
Thanks @webysther for the compliments and recommendations. I'll get these added.

@prassee the reason for sunsetting is very close to what webysther points out. I'm no longer in a position to use the project regularly, and between my current job, family, and limited free time in general, I'm not able to dedicate as much attention to this project as I'd like. 

On top of this, the ecosystem this project is built on (Node.js) is seeing a shift to a newer module system, and this will involve a lot of work to update these as things shift. 

So all things considered, given the sensitive nature of the application, I think its best to be transparent of its current state.

It is likely there will be a dependency with a vulnerability reported in the future, and SQLPad will be unable to move to the patched version because it is not written to handle the new module format.

In these cases I'll likely remove the dependency altogether. I expect SQLPad to gradually disappear. Development, but in reverse 😅
