### ISSUE TITLE
Abstraction for connection store and for persistent queries/results

### ISSUE THREAD

**Issue by Jan-M** [sqlpad/sqlpad#275]
Hi there, thus far sqlpad looks very promising and useful, I have deployed it on Kubernetes on trial basis using the Google login but now I need a bit more to make it even more useful.

There is issue #264 which at some point will probably also become important but there is two more urgent issues.

As I have some skill limits in JS I would like to see a bit more boilerplate and abstraction around how connections are stored. Basically I don't want to store them at all, I have a central source of possible connections (configs being pulled from Kubernetes) and want to enable users to pick any of them. For all those connections I basically preconfigure a user in PostgreSQL with limited privileges.

I can see from the models/Connection.js that it is rather simple, but maybe there is a preferred way how to implement this, hiding different storage implementations and selecting one based on environment variables.

I have not yet checked the history/query store but something similar there would help me, where I might be able to add the implementation towards redis/s3/postgres.

We have our own open source tools for provisioning PostgreSQL clusters on Kubernetes and it sounds like a great opportunity to somehow connect this to sqlpad so that new clusters are automatically added.

**Comment by rickbergfalk** [comment]
Sorry for the delay in responding to this. 

I'm a bit torn about having too many alternate implementations for the backend as it would add some complication to the maintenance and support of the project. However I'd prefer to see the project grow and meet the needs of its users.

Would swapping out the embedded nedb.js database with something like Postgres itself be enough of a help for extending SQLPad for your use case? 

If this is something that would be worth the effort and potential breakage, I'd be open to switching the backend implementation to something with flexible backend storage. For example, using a SQL ORM library and have the option of running SQLPad with a sqlite or postgres backend?

**Comment by Jan-M** [comment]
Hi Rick, no worries.

I am actually not looking for a replacement of nedb itself or your to put some work into storing stuff in PostgreSQL, something we actually are not looking for despite using PostgreSQL a lot.

For me it would be helpful to see how could/would add some code to make the nedb replacement easier.

One example after looking more into the code eg. could be replace nedb with some "http" backend, so relying on some 3rd party service that has findAll and findOne methods implemented. The base url could be an environment variable and everyone could just implement the "discovery" service.

I am already hacking something with our own API, maybe I find the time to push it and share this prototype to make it more clear.

**Comment by rickbergfalk** [comment]
Got it - I'll be on the lookout for that prototype :)

**Comment by Jan-M** [comment]
The most basic example now, not exactly what I described in regards to having some generic backend but I guess the picture may become a bit clearer.

We have the postgres-operator with an API endpoint that lists all postgres cluster names and databases withing, the result looks like:

```
{
 "cluster-1": ["foo", "bar"]
}
```

Where cluster-1 is resolvable hostname and foo and bar are databases with cluster-1.

I am now basically pointing sqlpad to this API for finding possible connection strings. This now auto populates all databases connectable within our Kubernetes playground cluster.

https://github.com/Jan-M/sqlpad/blob/demo-discovery/models/Connection.js#L7

Making this more generic would be similar, inject a URL config and make the findAll and findOne make a single request to some service populating the connection information.

**Comment by rickbergfalk** [comment]
Thanks for the example!

Is the postgres-operator API standard with Kubernetes or is that custom development?

I like the idea of being able to redirect an API call like this, but I think the response would almost need to be in the format of the SQLPad connection object if this is something to be merged upstream. The different variations of APIs to support could cause a lot of extra code to come into the project with no real way to test it. 

Would it be possible to have a service between SQLPad and the postgres-operator to map the postgres-operator response to the object format required by SQLPad? If so all that would be required is specifying the URL to call to override the findAll connections. 

I could understand the hesitation about that approach though since it'd be sending database credentials via a rest api.

If returning the full object via the rest api isn't an option... maybe this could also be done through some sort of plugin system or another node script communicating with SQLPad via thrift protocol or something?

I'm going to keep thinking about this :)

**Comment by Jan-M** [comment]
Yes I agree, the API sqlpad talks to should be aligned with the connection object, it would be up to us and others to implement a tiny service that sits in between.

Credentials could be included, depends a bit on the environment and data if that is how it would be done.

**Comment by oavdeev** [comment]
Just wanted to chime in and say that we'd really appreciate this feature too. It would be really great if we could run it without any local persistent storage at all in a docker container, using a cloud document store like DynamoDB or Firebase instead. And be able to use a bit of a custom code to pull DB connection strings from our secret storage, kind of like in Jan's use case (except we're not using Kubernetes).

**Comment by rickbergfalk** [comment]
Every so often when I go through and clean up issues I get stuck on this one, thinking about how it could be done. Unfortunately as  time went on APIs and data models expanded, and the backing database is more complex than it was when this issue was raised. Some APIs have filters, query results are persisted.

So I'm going to close this one out... 

There's a part of me that wonders what a fork of SQLPad would look like with no data storage requirements and a pluggable storage. Or maybe no storage at all if queries didn't need to be saved, auth was through another service, and connections were pulled from some API.

Perhaps I'm just nostalgic for when SQLPad had a less complex API and implementation than it has today 😅
