### ISSUE TITLE
Explore & View multiple databases - SQL Server

### ISSUE THREAD

**Issue by ameed** [sqlpad/sqlpad#846]
Hi Rick,
First of all, thanks for this awesome tool. I am writing here to request for a feature. I have been used to MS SQL Server Management Studio, where it is possible to connect to server and explore the databases under same connection. Is that likely possible here ? The reason i ask this is that i wish my users to be able to see which tables / views they have access to across databases and make SQL query join across databases, while being able to see field names while being connected with same connection.

For example, this query is joing two tables across two databases in same SQL instance

select
  [user].[fullname]
from
  [HRDB].[dbo].[User] [user]
  join [ERPDB].[dbo].[Order] [order] on [user].[userid] = [order].[createdby]

Many thanks
Ameed

**Comment by rickbergfalk** [comment]
Hi Ameed -- Thanks for the kind words!

It has been a while since I've worked with SQL Server, but I think this might be difficult to do well in SQLPad due to the way database connections are managed and modelled. 

Do you know if it is possible to connect to 1 database, but then reference another if SQLServer is set up accordingly? For example, if you connect to HRDB, can you do 

```sql
select
  [user].[fullname]
from
  -- (no HRDB here)
  [dbo].[User] [user]
  join [ERPDB].[dbo].[Order] [order] on [user].[userid] = [order].[createdby]
```

If this does work, the user experience still wouldn't be great with SQLPad unfortunately. The current architecture assumes there's only ever 1 database, so you'd only see the single database in the schema sidebar, and get a single database's autocomplete.

**Comment by euanmacinnes** [comment]
> Hi Ameed -- Thanks for the kind words!
> 
> It has been a while since I've worked with SQL Server, but I think this might be difficult to do well in SQLPad due to the way database connections are managed and modelled.
> 
> Do you know if it is possible to connect to 1 database, but then reference another if SQLServer is set up accordingly? For example, if you connect to HRDB, can you do
> 
> ```sql
> select
>   [user].[fullname]
> from
>   -- (no HRDB here)
>   [dbo].[User] [user]
>   join [ERPDB].[dbo].[Order] [order] on [user].[userid] = [order].[createdby]
> ```
> 
> If this does work, the user experience still wouldn't be great with SQLPad unfortunately. The current architecture assumes there's only ever 1 database, so you'd only see the single database in the schema sidebar, and get a single database's autocomplete.

You can howe



> Hi Rick,
> First of all, thanks for this awesome tool. I am writing here to request for a feature. I have been used to MS SQL Server Management Studio, where it is possible to connect to server and explore the databases under same connection. Is that likely possible here ? The reason i ask this is that i wish my users to be able to see which tables / views they have access to across databases and make SQL query join across databases, while being able to see field names while being connected with same connection.
> 
> For example, this query is joing two tables across two databases in same SQL instance
> 
> select
> [user].[fullname]
> from
> [HRDB].[dbo].[User] [user]
> join [ERPDB].[dbo].[Order] [order] on [user].[userid] = [order].[createdby]
> 
> Many thanks
> Ameed

In order to see the databases, you can run the query:

```
SELECT name, database_id, create_date  
FROM sys.databases ;  
```

Then save this as a "SHOW DATABASES" query in SQL Pad to quickly reference it (though might be nice to have some queries that are tagged accordingly appear directly in a menu, so it's quicker to reference them, (e.g. tagged with "SQL Server" if it's an SQL server connection and/or tagged with "Common").
