### ISSUE TITLE
downloaded excel can support over 50000 rows?

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#926]
When a query result have above 50000 rows, so the SQLPad only display 50000 rows, as same as the downloaded excel.
I think when download the excel, the excel can populate all result rows as it is, which even has above 50000 rows.

**Comment by rickbergfalk** [comment]
This could be tricky to implement. For something like this we'd need to stream query results to storage layer instead of buffer them in memory as is done today. This is possible with some drivers, but not all.

Perhaps this could be something that could be turned on per connection if the driver supports it like multi-statement transaction today?

**Comment by dengc367** [comment]
Yes, That need stream query results, like download big files. We can give an option/button for full rows download, when click the `Full Download` option, then can download, can only support the CSV format.

![image](https://user-images.githubusercontent.com/1353036/103269529-fff29a00-49f0-11eb-8740-e9c49cd4d95a.png)
