### ISSUE TITLE
Front End Integration

### ISSUE THREAD

**Issue by WLCPereira** [sqlpad/sqlpad#927]
Hi! First of all, congratulations for this project. I have an webapp also in React Js and I'd like to integrate sqlpad into that app. Is there a way to do this, without embed it through iframe?

**Comment by rickbergfalk** [comment]
Thanks @WLCPereira! Unfortunately there is not really a way to do this today. It might be possible if you wanted to use a custom build setup though.

Instead of using create-react-app used today, a custom webpack or roll-up config could be used to create a js module of a sqlpad component instead. This could get tricky though and I'm not really sure best way to go about it.

**Comment by WLCPereira** [comment]
Thanks for your response, @rickbergfalk .  Our team is studying a better way to do that integration.

**Comment by ytsaytak** [comment]
I have been attempting to do something similar but actually put the entire application in an iframe without much success.  It loads, but cannot get through the sign in screen.  Is there a security setting to update?
